.PHONY: clean All

All:
	@echo "----------Building project:[ smacofSSUI - Debug ]----------"
	@"$(MAKE)" -f  "smacofSSUI.mk"
clean:
	@echo "----------Cleaning project:[ smacofSSUI - Debug ]----------"
	@"$(MAKE)" -f  "smacofSSUI.mk" clean
